### ISSUE TITLE
'ws://localhost:3000/_next/webpack-hmr' failed: Invalid frame header. 

### ISSUE THREAD

**Issue by nwanoch** [MuxLabs/ws-ingest#23]
when I clone this repository and install dependencies, and start up the server, I get the Error code

websocket.js?a9be:60 WebSocket connection to 'ws://localhost:3000/_next/webpack-hmr' failed: Invalid frame header.

**Comment by cjpillsbury** [comment]
Hey @wenotch any chance you could give us more details? I haven't been able to reproduce locally. Here's what I did:
* cloned the repo locally via `git clone https://github.com/MuxLabs/wocket.git`
* ran `yarn` (aka `yarn install`) from the root
* ran `yarn dev` to start the server
* open the demo page in your browser of choice @ http://localhost:3000/

Things that could help:
* Doing a `git checkout . && rm -rf node_modules && yarn` on your currently failing local clone
* Attempting a full, "from scratch" clone+install+server start
* Clear steps of reproduction
* Whether or not the example page was loaded in a browser before starting the server via `yarn dev`
* Versions of any relevant tooling (node version, ffmpeg version, OS)
* The output of `yarn list` after an install, assuming you can still reproduce the error after the install


For what it's worth, I am seeing a potentially related issue under certain conditions that we'll want to look into:
```
Streaming socket connected
shit got closed, yo
FFmpeg child process closed, code null, signal SIGINT
error - uncaughtException: RangeError: Invalid WebSocket frame: invalid status code 18662
    at Receiver.controlMessage (/Users/cpillsbury/dev/projects/wocket/node_modules/next/dist/compiled/ws/index.js:1:18900)
    at Receiver.getData (/Users/cpillsbury/dev/projects/wocket/node_modules/next/dist/compiled/ws/index.js:1:17496)
    at Receiver.startLoop (/Users/cpillsbury/dev/projects/wocket/node_modules/next/dist/compiled/ws/index.js:1:14334)
    at Receiver._write (/Users/cpillsbury/dev/projects/wocket/node_modules/next/dist/compiled/ws/index.js:1:13674)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (/Users/cpillsbury/dev/projects/wocket/node_modules/next/dist/compiled/ws/index.js:1:44506)
    at Socket.emit (node:events:539:35)
    at addChunk (node:internal/streams/readable:315:12) {
  code: 'WS_ERR_INVALID_CLOSE_CODE',
  [Symbol(status-code)]: 1002
```

**Comment by nwanoch** [comment]
yeah, exactly that's the output on the development console. on browsers, it shows the error I gave earlier. 
the Ui looks ok until you create a stream and get that error.
